### ISSUE TITLE
mxbai-rerank-large-v1 starup error

### ISSUE THREAD

**Issue by edisonzf2020** [michaelfeil/infinity#219]
### System Info

infinity ver 0.0.32
python 3.10

### Information

- [ ] Docker
- [X] The CLI directly via pip

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

infinity_emb --model-name-or-path /opt/works/AI/ollama/ollama/mxbai-rerank-large-v1 --host 0.0.0.0 --port 8090 --log-level debug
INFO     2024-05-14 11:42:24,850 datasets INFO: PyTorch version 2.2.1 available.             config.py:58
INFO:     Started server process [1184226]
INFO:     Waiting for application startup.
INFO     2024-05-14 11:42:25,632 infinity_emb INFO:                                    select_model.py:54
         model=`/opt/works/AI/ollama/ollama/mxbai-rerank-large-v1` selected, using                       
         engine=`torch` and device=`None`                                                                
DEBUG    2024-05-14 11:42:25,633 infinity_emb DEBUG: model is a directory, opening     select_model.py:25
         config.json                                                                                     
ERROR:    Traceback (most recent call last):
  File "/home/fanai/.conda/envs/infinity/lib/python3.10/site-packages/starlette/routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/home/fanai/.conda/envs/infinity/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/home/fanai/.conda/envs/infinity/lib/python3.10/site-packages/infinity_emb/infinity_server.py", line 46, in lifespan
    app.model = AsyncEmbeddingEngine.from_args(engine_args)  # type: ignore
  File "/home/fanai/.conda/envs/infinity/lib/python3.10/site-packages/infinity_emb/engine.py", line 49, in from_args
    engine = cls(**asdict(engine_args), _show_deprecation_warning=False)
  File "/home/fanai/.conda/envs/infinity/lib/python3.10/site-packages/infinity_emb/engine.py", line 40, in __init__
    self._model, self._min_inference_t, self._max_inference_t = select_model(
  File "/home/fanai/.conda/envs/infinity/lib/python3.10/site-packages/infinity_emb/inference/select_model.py", line 62, in select_model
    loaded_engine = unloaded_engine.value(engine_args=engine_args)
  File "/home/fanai/.conda/envs/infinity/lib/python3.10/site-packages/infinity_emb/transformer/crossencoder/torch.py", line 38, in __init__
    super().__init__(
  File "/home/fanai/.conda/envs/infinity/lib/python3.10/site-packages/sentence_transformers/cross_encoder/CrossEncoder.py", line 81, in __init__
    self.model = AutoModelForSequenceClassification.from_pretrained(
TypeError: transformers.models.auto.auto_factory._BaseAutoModelClass.from_pretrained() got multiple values for keyword argument 'trust_remote_code'

ERROR:    Application startup failed. Exiting.

### Expected behavior

starup ok

**Comment by michaelfeil** [comment]
Got it! Thats because of the sentence-transformer with breaking change in 2.6 vs 2.7. Fixed on latest master.

**Comment by michaelfeil** [comment]
Should be fixed now with `pip install infinity_emb[all]==0.0.33`, the current sentence-transformers is pulled correctly.
