### ISSUE TITLE
[Benchmark] - embedding quantization

### ISSUE THREAD

**Issue by michaelfeil** [michaelfeil/infinity#250]
### System Info

0.0.40 shipped the first version of embedding quant.

`--embedding-dtype int8`

This Issue is looking for testers, to verify the real life performance of these features at real datasets.

### Information

- [X] Docker
- [X] The CLI directly via pip

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

-

### Expected behavior

E.g. delivering a benchmark of int8 quantization - can be added under `./docs`

**Comment by michaelfeil** [comment]
@mahiro72 Expressed interest in working on this fyi!
