### ISSUE TITLE
test

### ISSUE THREAD

**Issue by michaelfeil** [michaelfeil/infinity#264]
### System Info

test

### Information

- [ ] Docker
- [ ] The CLI directly via pip

### Tasks

- [ ] An officially supported command
- [X] My own modifications

### Reproduction

How do i install infinity?

### Expected behavior

-
