### ISSUE TITLE
Request input data type(array of integer) is not compatible with openai embedding api

### ISSUE THREAD

**Issue by c2j** [michaelfeil/infinity#295]
### System Info

infinity 0.0.51 in Python 3.11, Ubuntu. 

As openai api ref( https://platform.openai.com/docs/api-reference/embeddings/create ), the request arg `input` could be string or array

string: The string that will be turned into an embedding.
array: The array of strings that will be turned into an embedding.
array: The array of integers that will be turned into an embedding.
array: The array of arrays containing integers that will be turned into an embedding.

### Information

- [ ] Docker
- [X] The CLI directly via pip

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

Can reproduce in following request:
```
from openai import OpenAI
client = OpenAI(max_retries=5)
response = client.embeddings.create(input=[100,201,301], model=embedding_model) 
```

Openai can return embedding, but infinity_emb throw error:
```
UnprocessableEntityError: Error code: 422 - {'detail': [{'type': 'string_type', 'loc': ['body', 'input', 'list[constrained-str]', 0], 'msg': 'Input should be a valid string', 'input': 100}, {'type': 'string_type', 'loc': ['body', 'input', 'list[constrained-str]', 1], 'msg': 'Input should be a valid string', 'input': 201}, {'type': 'string_type', 'loc': ['body', 'input', 'list[constrained-str]', 2], 'msg': 'Input should be a valid string', 'input': 301}, {'type': 'string_type', 'loc': ['body', 'input', 'constrained-str'], 'msg': 'Input should be a valid string', 'input': [100, 201, 301]}]}
```

### Expected behavior

support array of integer so that compatible with openai embedding api

**Comment by michaelfeil** [comment]
OpenAI uses a different tokenizer. The numbers would require detokenizing and re tokenizing. This is not desired, and has been discussed in other issues. Therefore closed.
