### ISSUE TITLE
Infinity Docs Are Offline

### ISSUE THREAD

**Issue by Senslyze-Docuwise** [michaelfeil/infinity#300]
### System Info

Irrelevant *

### Information

- [ ] Docker
- [ ] The CLI directly via pip

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

1. Open https://michaelfeil.eu/infinity/

### Expected behavior

Docs Should open. 
Currently it shows 

404
There isn't a GitHub Pages site here.

If you're trying to publish one, [read the full documentation](https://help.github.com/pages/) to learn how to set up GitHub Pages for your repository, organization, or user account.

**Comment by michaelfeil** [comment]
https://michaelfeil.gothub.io/infinity

**Comment by janakm-senslyze** [comment]
Thank You!
