### ISSUE TITLE
When implementing with Python API, using asynchronous with engine will consume 500ms of time

### ISSUE THREAD

**Issue by Myson850** [michaelfeil/infinity#321]
### System Info

In the Python version, I found that engine. embedded takes 20ms to complete, but waiting for asyncio.run to finish takes 520ms, with the majority of the time spent on asynchronous with engine. This is completely different from the infinity emb v2 method, which takes 20ms to complete

### Information

- [ ] Docker
- [ ] The CLI directly via pip

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

.

### Expected behavior

.

**Comment by michaelfeil** [comment]
Is your code mainly “synchronous” or are you  writing your application in async?
If Syncronous, give 
https://github.com/michaelfeil/embed a try (& start it off you like it ;))

**Comment by Myson850** [comment]
I integrated the code into an asynchronous framework

> 您的代码主要是“同步”的，还是您以异步方式编写的应用程序？ 如果是开始同步的，请尝试 https://github.com/michaelfeil/embed（如果您喜欢，请立即使用;)）

**Comment by michaelfeil** [comment]
@Myson850 how are you using it?

```python
from infinity_emb import AsyncEngineArray, EngineArgs, AsyncEmbeddingEngine

sentences = ["Embed this is sentence via Infinity.", "Paris is in France."]
array = AsyncEngineArray.from_args([
  EngineArgs(model_name_or_path = "BAAI/bge-small-en-v1.5", engine="torch", embedding_dtype="float32", dtype="auto")
])

async def embed_text(engine: AsyncEmbeddingEngine): 
    # or handle the async start / stop yourself.
    await engine.astart()
    embeddings, usage = await engine.embed(sentences=sentences)

for i in range(100):
    await embed_text(..)

# sometimes later
await engine.astop()
```

**Comment by michaelfeil** [comment]
dont use the `async with engine` if you restart it often. use `astart` and `astop` as few times as possible,. `asyncio.run()` is something you done ONCE in the runtime of the program, not multiple times.

**Comment by michaelfeil** [comment]
dont use the `async with engine` if you restart it often. use `astart` and `astop` as few times as possible,. `asyncio.run()` is something you done ONCE in the runtime of the program, not multiple times.

**Comment by michaelfeil** [comment]
Assuming this can be closed, as there is no further activity?
