### ISSUE TITLE
Breaking CI / Python installs

### ISSUE THREAD

**Issue by michaelfeil** [michaelfeil/infinity#415]
### System Info

I am not sure why the CI keeps breaking. 

Currently, the downloaded packages are cached to Github  / via GH actions.

Example:
https://github.com/michaelfeil/infinity/actions/runs/11286542174/job/31391069817

Observation: Maybe happens when there is a concurrent PR running e.g. on a branch & on the main branch

### Information

- [ ] Docker
- [X] The CLI directly via pip

### Tasks

- [ ] An officially supported command
- [X] My own modifications

### Reproduction

dd

### Expected behavior

d

**Comment by wirthual** [comment]
Similar type of Error of CI observed [here](https://github.com/michaelfeil/infinity/actions/runs/11472064124/job/31924021168?pr=438)
