### ISSUE TITLE
How to disable posthog for send anonymous data to external domain

### ISSUE THREAD

**Issue by AlexBlack2202** [michaelfeil/infinity#428]
### System Info

i use the lasted version and i see that there are many request to  eu.i.posthog.com, it is not legal for user .

Can you disable it by default?

### Information

- [ ] Docker
- [ ] The CLI directly via pip

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

start new emb model

### Expected behavior

disable send data to posthog.com

**Comment by michaelfeil** [comment]
@AlexBlack2202 https://michaelfeil.eu/infinity/0.0.64/telemetry

You can disable tracking like the following:

# set 
export DO_NOT_TRACK="1"
# infinity specific setting
export INFINITY_ANONYMOUS_USAGE_STATS="0"

Is similar to e.g. how other projects collect stats:
- https://docs.vllm.ai/en/latest/serving/usage_stats.html#usage-stats-collection
- https://docs.ray.io/en/latest/cluster/usage-stats.html

Infinity collects currently info on which:
- GPU card is used, helps to know if e.g. flash-attn build would be useful / worth the effort, or not worth it because most card are still 
- devices: is mps or neuron used often
- CLI args, to deprecate old ones or less popular ones such as onnx/tensorrt gpu + optimum or ctranslate2
