### ISSUE TITLE
License Link Broken in Readme

### ISSUE THREAD

**Issue by niranjan-kurhade** [michaelfeil/infinity#445]
### System Info

The License link is broken in README
It takes to a 404 file not found page. 
![image](https://github.com/user-attachments/assets/335ef34c-1651-45d4-b9dc-cdadc8bb2418)
 

### Information

- [ ] Docker
- [ ] The CLI directly via pip

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

1. Go to README.md
2. Click on License MIT

### Expected behavior

Should redirect to correct link
