### ISSUE TITLE
OpenAIEmbeddings is flattening out the embeddings received from colpali models.

### ISSUE THREAD

**Issue by S1LV3RJ1NX** [michaelfeil/infinity#450]
### System Info

Using infinity 0.0.67

### Information

- [ ] Docker
- [ ] The CLI directly via pip

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

When I try use `colpali` models via REST service -> Embedding dimension is 262*128 which is correct.
But when I use OpenAI, it flattens out to shape -> 33536 which is incorrect. How do we fix this?

Code Snippets:
```
import requests

    url = 'http://localhost:7997/embeddings'
    headers = {
        'accept': 'application/json',
        'Authorization': 'Bearer sk-infinity-svc',
        'Content-Type': 'application/json'
    }
    data = {
        "model": "michaelfeil/colpali-v12-random-testing",
        "encoding_format": "float",
        "user": "string",
        "input": [
            # "http://images.cocodataset.org/val2017/000000039769.jpg"
            base64_image
        ],
        "modality": "image"
    }

    response = requests.post(url, headers=headers, json=data)

    embedding = response.json()['data'][0]['embedding']
    embedding = np.array(embedding)
    print(embedding.shape)
```

With OpenAI
```
client = OpenAI(
        api_key="sk-infinity-svc",
        base_url="http://localhost:7997"
    )


    response = client.embeddings.create(
        model="michaelfeil/colpali-v12-random-testing",
        input=[base64_image],
        extra_body={"modality": "image"}
    )

    embedding = response.data[0].embedding
    embedding = np.array(embedding)
    print(embedding.shape)
```

### Expected behavior

In both cases dimensions should be 262*128

**Comment by wirthual** [comment]
Hi @S1LV3RJ1NX ,

interesting find. Seems like the `openai-python` package is applying some sort of flattening [here](https://github.com/openai/openai-python/blob/891e1c17b7fecbae34d1915ba90c15ddece807f9/src/openai/resources/embeddings.py#L219) if the `encoding_format` is not explicit specified?

If I add ` encoding_format="float"` the response is in the expected shape.

```python
from openai import OpenAI
import base64
import requests
import numpy as np

url = "https://github.com/michaelfeil/infinity/raw/06fd1f4d8f0a869f4482fc1c78b62a75ccbb66a1/docs/assets/cats_coco_sample.jpg"

response = requests.get(url)
base64_image = base64.b64encode(response.content).decode('utf-8')

client = OpenAI(
        api_key="sk-infinity-svc",
        base_url="http://localhost:7997"
    )


response = client.embeddings.create(
    model="michaelfeil/cshapeolpali-v12-random-testing",
    input=["data:image/jpeg;base64," + base64_image],
    extra_body={"modality": "image"},
    encoding_format="float"
)

embedding = response.data[0].embedding
embedding = np.array(embedding)
print(embedding.shape)
```

This resuls in shape `(262, 128)`
`

**Comment by michaelfeil** [comment]
Yes! It’s the fault of OpenAI embeddings, and there is sadly not much we can do here. You can perform a simple reshape via numpy. 
You can query the hidden dimension via a simple post calll.

**Comment by S1LV3RJ1NX** [comment]
Thanks!!

**Comment by S1LV3RJ1NX** [comment]
Do you have any idea on: https://github.com/BerriAI/litellm/issues/6525

**Comment by S1LV3RJ1NX** [comment]
@michaelfeil just another query can we host colqwen model on mac?

**Comment by michaelfeil** [comment]
@S1LV3RJ1NX As in: colqwen on torch + mps device?

**Comment by S1LV3RJ1NX** [comment]
Yes.
