### ISSUE TITLE
requires device with capability > (8, 0) but your GPU has capability (7, 5) (too old)

### ISSUE THREAD

**Issue by HighSec-org** [michaelfeil/infinity#463]
### System Info

OS version: linux
Model being used: dunzhang/stella_en_400M_v5
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.42.06              Driver Version: 555.42.06      CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
Hardware used: Quadro RTX 8000
PyTorch version 2.5.1

### Information

- [ ] Docker + cli
- [X] pip + cli
- [ ] pip + usage of Python interface

### Tasks

- [X] An officially supported CLI command
- [ ] My own modifications

### Reproduction

infinity_emb v2 --device cuda --model-id dunzhang/stella_en_400M_v5

**Produces error:**
NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(1, 3, 16, 64) (torch.bfloat16)
     key         : shape=(1, 3, 16, 64) (torch.bfloat16)
     value       : shape=(1, 3, 16, 64) (torch.bfloat16)
     attn_bias   : <class 'xformers.ops.fmha.attn_bias.BlockDiagonalMask'>
     p           : 0.0
`fa2F@2.6.3` is not supported because:
    requires device with capability > (8, 0) but your GPU has capability (7, 5) (too old)
    bf16 is only supported on A100+ GPUs
`cutlassF-pt` is not supported because:
    bf16 is only supported on A100+ GPUs
    
**However, the package says they are available**
python -m xformers.info 

xFormers 0.0.29.dev939
memory_efficient_attention.ckF:                    unavailable
memory_efficient_attention.ckB:                    unavailable
memory_efficient_attention.ck_decoderF:            unavailable
memory_efficient_attention.ck_splitKF:             unavailable
**memory_efficient_attention.cutlassF-pt:            available**
memory_efficient_attention.cutlassB-pt:            available
**memory_efficient_attention.fa2F@2.6.3:             available**
memory_efficient_attention.fa2B@2.6.3:             available
memory_efficient_attention.fa3F@0.0.0:             unavailable
memory_efficient_attention.fa3B@0.0.0:             unavailable
memory_efficient_attention.triton_splitKF:         available
indexing.scaled_index_addF:                        unavailable
indexing.scaled_index_addB:                        unavailable
indexing.index_select:                             unavailable
sequence_parallel_fused.write_values:              available
sequence_parallel_fused.wait_values:               available
sequence_parallel_fused.cuda_memset_32b_async:     available
sp24.sparse24_sparsify_both_ways:                  available
sp24.sparse24_apply:                               available
sp24.sparse24_apply_dense_output:                  available
sp24._sparse24_gemm:                               available
sp24._cslt_sparse_mm_search@0.6.2:                 available
sp24._cslt_sparse_mm@0.6.2:                        available
swiglu.dual_gemm_silu:                             available
swiglu.gemm_fused_operand_sum:                     available
swiglu.fused.p.cpp:                                available
is_triton_available:                               False
pytorch.version:                                   2.5.1+cu124
pytorch.cuda:                                      available
gpu.compute_capability:                            7.5
gpu.name:                                          Quadro RTX 8000
dcgm_profiler:                                     unavailable
build.info:                                        available
build.cuda_version:                                1201
build.hip_version:                                 None
build.python_version:                              3.10.15
build.torch_version:                               2.5.1+cu121
build.env.TORCH_CUDA_ARCH_LIST:                    6.0+PTX 7.0 7.5 8.0+PTX 9.0a
build.env.PYTORCH_ROCM_ARCH:                       None
build.env.XFORMERS_BUILD_TYPE:                     Release
build.env.XFORMERS_ENABLE_DEBUG_ASSERTIONS:        None
build.env.NVCC_FLAGS:                              -allow-unsupported-compiler
build.env.XFORMERS_PACKAGE_FROM:                   wheel-main
build.nvcc_version:                                12.1.66
source.privacy:                                    open source

so it seems that 8.0+PTX needs to be added somewhere, because it shows _fa2F@2.6.3 and cutlassF-pt are available_, but only checks for  TORCH_CUDA_ARCH 8.0 and fails on 8.0+PTX

**Comment by S1LV3RJ1NX** [comment]
@michaelfeil - How do we deploy multiple models with the command mentioned above?

**Comment by S1LV3RJ1NX** [comment]
Edit:
This command is working:
```
v2 --model-id dunzhang/stella_en_400M_v5 --revision "refs/pr/24" --model-id colbert-ir/colbertv2.0 --revision "refs/heads/main" --model-id mixedbread-ai/mxbai-rerank-xsmall-v1 --revision "refs/heads/main" --model-id michaelfeil/colqwen2-v0.1 --revision "refs/heads/main"
```

There should be cleaner way though.

**Comment by michaelfeil** [comment]
@S1LV3RJ1NX what would you recommend a clearer way?

**Comment by S1LV3RJ1NX** [comment]
Something like all model ids separated by semicolon with a single flag.
And all revisions, the last revision should be broadcasted to the rest of
the models.

**Comment by michaelfeil** [comment]
You can do a similar thing with semi-colon separation with the environment variables.

typer has automatic type validation for arg such as “—batch-size 8” so would be difficult to validate “batch-size 8;16” out of the box.

**Comment by qdrddr** [comment]
Cannot run `stella_en_1.5B_v5` on my macOS 15 either

**Comment by qdrddr** [comment]
This model supports multiple dimensions, how do I choose a dimensionality for a model with infinity? @michaelfeil

**Comment by wirthual** [comment]
Hi,
as per the instructions in the repo, they recommend doing this:
```
# ！The default dimension is 1024, if you need other dimensions, please clone the model and modify `modules.json` to replace `2_Dense_1024` with another dimension, e.g. `2_Dense_256` or `2_Dense_8192` !
```

So I guess you need to clone it and run it from a local copy with the desired modifications.
