### ISSUE TITLE
BetterTransformer is not available for model fine-tuned on GTE-base

### ISSUE THREAD

**Issue by Tejaswgupta** [michaelfeil/infinity#493]
### System Info

OS: Linux
Model: fine-tuned on GTE-base using sentence-transformers
Hardware: Nvidia A100

### Information

- [ ] Docker + cli
- [ ] pip + cli
- [X] pip + usage of Python interface

### Tasks

- [X] An officially supported CLI command
- [ ] My own modifications

### Reproduction

Code:
```
import asyncio
from infinity_emb import AsyncEngineArray, EngineArgs, AsyncEmbeddingEngine

sentences = ["Embed this is sentence via Infinity.", "Paris is in France."]
array = AsyncEngineArray.from_args([
  EngineArgs(model_name_or_path = "Tejasw1/votum-case-law-v1", engine="torch", embedding_dtype="float32", dtype="auto")
])

async def embed_text(engine: AsyncEmbeddingEngine): 
    async with engine: 
        embeddings, usage = await engine.embed(sentences=sentences)
    # or handle the async start / stop yourself.
    await engine.astart()
    embeddings, usage = await engine.embed(sentences=sentences)
    await engine.astop()
asyncio.run(embed_text(array[0]))
```

Logs:
```
<pre style="white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace"><span style="color: #800000; text-decoration-color: #800000; font-weight: bold">ERROR   </span> <span style="color: #008080; text-decoration-color: #008080; font-weight: bold">2024</span>-<span style="color: #008080; text-decoration-color: #008080; font-weight: bold">12</span>-<span style="color: #008080; text-decoration-color: #008080; font-weight: bold">09</span> <span style="color: #00ff00; text-decoration-color: #00ff00; font-weight: bold">07:44:54</span>,<span style="color: #008080; text-decoration-color: #008080; font-weight: bold">988</span> infinity_emb ERROR: BetterTransformer is not available for      <a href="file:///home/azureuser/miniconda3/lib/python3.11/site-packages/infinity_emb/transformer/acceleration.py" target="_blank"><span style="color: #7f7f7f; text-decoration-color: #7f7f7f">acceleration.py</span></a><span style="color: #7f7f7f; text-decoration-color: #7f7f7f">:</span><a href="file:///home/azureuser/miniconda3/lib/python3.11/site-packages/infinity_emb/transformer/acceleration.py#62" target="_blank"><span style="color: #7f7f7f; text-decoration-color: #7f7f7f">62</span></a>
         model: <span style="font-weight: bold">&lt;</span><span style="color: #ff00ff; text-decoration-color: #ff00ff; font-weight: bold">class</span><span style="color: #000000; text-decoration-color: #000000"> </span>                                                                          <span style="color: #7f7f7f; text-decoration-color: #7f7f7f">                  </span>
         <span style="color: #008000; text-decoration-color: #008000">'transformers_modules.Alibaba-NLP.new-impl.40ced75c3017eb27626c9d4ea981bde21a2662f4.mod</span> <span style="color: #7f7f7f; text-decoration-color: #7f7f7f">                  </span>
         <span style="color: #008000; text-decoration-color: #008000">eling.NewModel'</span><span style="font-weight: bold">&gt;</span> The model type new is not yet supported to be used with                <span style="color: #7f7f7f; text-decoration-color: #7f7f7f">                  </span>
         BetterTransformer. Feel free to open an issue at                                        <span style="color: #7f7f7f; text-decoration-color: #7f7f7f">                  </span>
         <span style="color: #0000ff; text-decoration-color: #0000ff; text-decoration: underline">https://github.com/huggingface/optimum/issues</span> if you would like this model type to be   <span style="color: #7f7f7f; text-decoration-color: #7f7f7f">                  </span>
         supported. Currently supported models are: <span style="color: #800080; text-decoration-color: #800080; font-weight: bold">dict_keys</span><span style="font-weight: bold">([</span><span style="color: #008000; text-decoration-color: #008000">'albert'</span>, <span style="color: #008000; text-decoration-color: #008000">'bark'</span>, <span style="color: #008000; text-decoration-color: #008000">'bart'</span>, <span style="color: #008000; text-decoration-color: #008000">'bert'</span>, <span style="color: #7f7f7f; text-decoration-color: #7f7f7f">                  </span>
         <span style="color: #008000; text-decoration-color: #008000">'bert-generation'</span>, <span style="color: #008000; text-decoration-color: #008000">'blenderbot'</span>, <span style="color: #008000; text-decoration-color: #008000">'bloom'</span>, <span style="color: #008000; text-decoration-color: #008000">'camembert'</span>, <span style="color: #008000; text-decoration-color: #008000">'blip-2'</span>, <span style="color: #008000; text-decoration-color: #008000">'clip'</span>, <span style="color: #008000; text-decoration-color: #008000">'codegen'</span>,     <span style="color: #7f7f7f; text-decoration-color: #7f7f7f">                  </span>
         <span style="color: #008000; text-decoration-color: #008000">'data2vec-text'</span>, <span style="color: #008000; text-decoration-color: #008000">'deit'</span>, <span style="color: #008000; text-decoration-color: #008000">'distilbert'</span>, <span style="color: #008000; text-decoration-color: #008000">'electra'</span>, <span style="color: #008000; text-decoration-color: #008000">'ernie'</span>, <span style="color: #008000; text-decoration-color: #008000">'fsmt'</span>, <span style="color: #008000; text-decoration-color: #008000">'gpt2'</span>, <span style="color: #008000; text-decoration-color: #008000">'gptj'</span>,      <span style="color: #7f7f7f; text-decoration-color: #7f7f7f">                  </span>
         <span style="color: #008000; text-decoration-color: #008000">'gpt_neo'</span>, <span style="color: #008000; text-decoration-color: #008000">'gpt_neox'</span>, <span style="color: #008000; text-decoration-color: #008000">'hubert'</span>, <span style="color: #008000; text-decoration-color: #008000">'layoutlm'</span>, <span style="color: #008000; text-decoration-color: #008000">'m2m_100'</span>, <span style="color: #008000; text-decoration-color: #008000">'marian'</span>, <span style="color: #008000; text-decoration-color: #008000">'markuplm'</span>, <span style="color: #008000; text-decoration-color: #008000">'mbart'</span>,  <span style="color: #7f7f7f; text-decoration-color: #7f7f7f">                  </span>
         <span style="color: #008000; text-decoration-color: #008000">'opt'</span>, <span style="color: #008000; text-decoration-color: #008000">'pegasus'</span>, <span style="color: #008000; text-decoration-color: #008000">'rembert'</span>, <span style="color: #008000; text-decoration-color: #008000">'prophetnet'</span>, <span style="color: #008000; text-decoration-color: #008000">'roberta'</span>, <span style="color: #008000; text-decoration-color: #008000">'roc_bert'</span>, <span style="color: #008000; text-decoration-color: #008000">'roformer'</span>,           <span style="color: #7f7f7f; text-decoration-color: #7f7f7f">                  </span>
         <span style="color: #008000; text-decoration-color: #008000">'splinter'</span>, <span style="color: #008000; text-decoration-color: #008000">'tapas'</span>, <span style="color: #008000; text-decoration-color: #008000">'t5'</span>, <span style="color: #008000; text-decoration-color: #008000">'vilt'</span>, <span style="color: #008000; text-decoration-color: #008000">'vit'</span>, <span style="color: #008000; text-decoration-color: #008000">'vit_mae'</span>, <span style="color: #008000; text-decoration-color: #008000">'vit_msn'</span>, <span style="color: #008000; text-decoration-color: #008000">'wav2vec2'</span>,             <span style="color: #7f7f7f; text-decoration-color: #7f7f7f">                  </span>
         <span style="color: #008000; text-decoration-color: #008000">'xlm-roberta'</span>, <span style="color: #008000; text-decoration-color: #008000">'yolos'</span><span style="font-weight: bold">])</span>.. Continue without bettertransformer modeling code.            <span style="color: #7f7f7f; text-decoration-color: #7f7f7f">                  </span>
         Traceback <span style="font-weight: bold">(</span>most recent call last<span style="font-weight: bold">)</span>:                                                      <span style="color: #7f7f7f; text-decoration-color: #7f7f7f">                  </span>
           File                                                                                  <span style="color: #7f7f7f; text-decoration-color: #7f7f7f">                  </span>
         <span style="color: #008000; text-decoration-color: #008000">"/home/azureuser/miniconda3/lib/python3.11/site-packages/infinity_emb/transformer/accel</span> <span style="color: #7f7f7f; text-decoration-color: #7f7f7f">                  </span>
         <span style="color: #008000; text-decoration-color: #008000">eration.py"</span>, line <span style="color: #008080; text-decoration-color: #008080; font-weight: bold">58</span>, in to_bettertransformer                                           <span style="color: #7f7f7f; text-decoration-color: #7f7f7f">                  </span>
             model = <span style="color: #800080; text-decoration-color: #800080; font-weight: bold">BetterTransformer.transform</span><span style="font-weight: bold">(</span>model<span style="font-weight: bold">)</span>                                          <span style="color: #7f7f7f; text-decoration-color: #7f7f7f">                  </span>
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                          <span style="color: #7f7f7f; text-decoration-color: #7f7f7f">                  </span>
           File <span style="color: #008000; text-decoration-color: #008000">"/home/azureuser/miniconda3/lib/python3.11/contextlib.py"</span>, line <span style="color: #008080; text-decoration-color: #008080; font-weight: bold">81</span>, in inner     <span style="color: #7f7f7f; text-decoration-color: #7f7f7f">                  </span>
             return <span style="color: #800080; text-decoration-color: #800080; font-weight: bold">func</span><span style="font-weight: bold">(</span>*args, **kwds<span style="font-weight: bold">)</span>                                                          <span style="color: #7f7f7f; text-decoration-color: #7f7f7f">                  </span>
                    ^^^^^^^^^^^^^^^^^^^                                                          <span style="color: #7f7f7f; text-decoration-color: #7f7f7f">                  </span>
           File                                                                                  <span style="color: #7f7f7f; text-decoration-color: #7f7f7f">                  </span>
         <span style="color: #008000; text-decoration-color: #008000">"/home/azureuser/miniconda3/lib/python3.11/site-packages/optimum/bettertransformer/tran</span> <span style="color: #7f7f7f; text-decoration-color: #7f7f7f">                  </span>
         <span style="color: #008000; text-decoration-color: #008000">sformation.py"</span>, line <span style="color: #008080; text-decoration-color: #008080; font-weight: bold">247</span>, in transform                                                  <span style="color: #7f7f7f; text-decoration-color: #7f7f7f">                  </span>
             raise <span style="color: #800080; text-decoration-color: #800080; font-weight: bold">NotImplementedError</span><span style="font-weight: bold">(</span>                                                          <span style="color: #7f7f7f; text-decoration-color: #7f7f7f">                  </span>
         NotImplementedError: The model type new is not yet supported to be used with            <span style="color: #7f7f7f; text-decoration-color: #7f7f7f">                  </span>
         BetterTransformer. Feel free to open an issue at                                        <span style="color: #7f7f7f; text-decoration-color: #7f7f7f">                  </span>
         <span style="color: #0000ff; text-decoration-color: #0000ff; text-decoration: underline">https://github.com/huggingface/optimum/issues</span> if you would like this model type to be   <span style="color: #7f7f7f; text-decoration-color: #7f7f7f">                  </span>
         supported. Currently supported models are: <span style="color: #800080; text-decoration-color: #800080; font-weight: bold">dict_keys</span><span style="font-weight: bold">([</span><span style="color: #008000; text-decoration-color: #008000">'albert'</span>, <span style="color: #008000; text-decoration-color: #008000">'bark'</span>, <span style="color: #008000; text-decoration-color: #008000">'bart'</span>, <span style="color: #008000; text-decoration-color: #008000">'bert'</span>, <span style="color: #7f7f7f; text-decoration-color: #7f7f7f">                  </span>
         <span style="color: #008000; text-decoration-color: #008000">'bert-generation'</span>, <span style="color: #008000; text-decoration-color: #008000">'blenderbot'</span>, <span style="color: #008000; text-decoration-color: #008000">'bloom'</span>, <span style="color: #008000; text-decoration-color: #008000">'camembert'</span>, <span style="color: #008000; text-decoration-color: #008000">'blip-2'</span>, <span style="color: #008000; text-decoration-color: #008000">'clip'</span>, <span style="color: #008000; text-decoration-color: #008000">'codegen'</span>,     <span style="color: #7f7f7f; text-decoration-color: #7f7f7f">                  </span>
         <span style="color: #008000; text-decoration-color: #008000">'data2vec-text'</span>, <span style="color: #008000; text-decoration-color: #008000">'deit'</span>, <span style="color: #008000; text-decoration-color: #008000">'distilbert'</span>, <span style="color: #008000; text-decoration-color: #008000">'electra'</span>, <span style="color: #008000; text-decoration-color: #008000">'ernie'</span>, <span style="color: #008000; text-decoration-color: #008000">'fsmt'</span>, <span style="color: #008000; text-decoration-color: #008000">'gpt2'</span>, <span style="color: #008000; text-decoration-color: #008000">'gptj'</span>,      <span style="color: #7f7f7f; text-decoration-color: #7f7f7f">                  </span>
         <span style="color: #008000; text-decoration-color: #008000">'gpt_neo'</span>, <span style="color: #008000; text-decoration-color: #008000">'gpt_neox'</span>, <span style="color: #008000; text-decoration-color: #008000">'hubert'</span>, <span style="color: #008000; text-decoration-color: #008000">'layoutlm'</span>, <span style="color: #008000; text-decoration-color: #008000">'m2m_100'</span>, <span style="color: #008000; text-decoration-color: #008000">'marian'</span>, <span style="color: #008000; text-decoration-color: #008000">'markuplm'</span>, <span style="color: #008000; text-decoration-color: #008000">'mbart'</span>,  <span style="color: #7f7f7f; text-decoration-color: #7f7f7f">                  </span>
         <span style="color: #008000; text-decoration-color: #008000">'opt'</span>, <span style="color: #008000; text-decoration-color: #008000">'pegasus'</span>, <span style="color: #008000; text-decoration-color: #008000">'rembert'</span>, <span style="color: #008000; text-decoration-color: #008000">'prophetnet'</span>, <span style="color: #008000; text-decoration-color: #008000">'roberta'</span>, <span style="color: #008000; text-decoration-color: #008000">'roc_bert'</span>, <span style="color: #008000; text-decoration-color: #008000">'roformer'</span>,           <span style="color: #7f7f7f; text-decoration-color: #7f7f7f">                  </span>
         <span style="color: #008000; text-decoration-color: #008000">'splinter'</span>, <span style="color: #008000; text-decoration-color: #008000">'tapas'</span>, <span style="color: #008000; text-decoration-color: #008000">'t5'</span>, <span style="color: #008000; text-decoration-color: #008000">'vilt'</span>, <span style="color: #008000; text-decoration-color: #008000">'vit'</span>, <span style="color: #008000; text-decoration-color: #008000">'vit_mae'</span>, <span style="color: #008000; text-decoration-color: #008000">'vit_msn'</span>, <span style="color: #008000; text-decoration-color: #008000">'wav2vec2'</span>,             <span style="color: #7f7f7f; text-decoration-color: #7f7f7f">                  </span>
         <span style="color: #008000; text-decoration-color: #008000">'xlm-roberta'</span>, <span style="color: #008000; text-decoration-color: #008000">'yolos'</span><span style="font-weight: bold">])</span>.                                                               <span style="color: #7f7f7f; text-decoration-color: #7f7f7f">                  </span>
</pre>
```

**Comment by michaelfeil** [comment]
Thanks for flagging. That's fine, gte is not implemented. Just disable via --no-bettertransformer in the cli, if you do not want to see the warning message.

**Comment by Tejaswgupta** [comment]
Thank you!
