### ISSUE TITLE
torch.OutOfMemoryError: CUDA out of memory. when serving NV-Embed-V2 on 8 40G A100 GPUs

### ISSUE THREAD

**Issue by atanikan** [michaelfeil/infinity#498]
### System Info

Infinity version: 0.0.71
```
[openinference_svc@sophia-gpu-06 ~]$ conda activate /eagle/argonne_tpc/inference-gateway/infinityv0.0.71
(2024-08-08//eagle/argonne_tpc/inference-gateway/infinityv0.0.71) [openinference_svc@sophia-gpu-06 ~]$ infinity_emb v2 --help
INFO     2024-12-16 05:30:55,856 datasets INFO: PyTorch version 2.5.1 available.                                                                                                                          config.py:54
```
       OS version:     linux
       Model being used:  NV-Embed-V2                                                                                                                                                                                                                                                               
       Hardware: 8 NIVIDIA 40GB A100 GPUs

Is there tensor parallelism or some other way to mitigate memory issues when serving the model. We see it after a few requests in a tool calling example.

### Information

- [ ] Docker + cli
- [ ] pip + cli
- [X] pip + usage of Python interface

### Tasks

- [X] An officially supported CLI command
- [ ] My own modifications

### Reproduction

Model serving.
`infinity_emb v2 --host 127.0.0.1 --port 8000 --model-id nvidia/NV-Embed-v2 --device cuda --trust-remote-code
`
Example call:

```
from openai import OpenAI
import base64
from langchain_chroma import Chroma
from authinfinityembeddings import AuthInfinityEmbeddings

# Load access token                                                                                                  
with open('access_token.txt', 'r') as file:
  access_token = file.read().strip()

url   = "https://data-portal-dev.cels.anl.gov/resource_server/sophia/infinity/v1"
model = "nvidia/NV-Embed-v2"


# Using Chroma to construct a vector database                                                                        

embedding = AuthInfinityEmbeddings(infinity_api_url = url,model = model, token = access_token)

db  = Chroma.from_texts(['The food was delicious and the waiter..','The cat was big'], embedding)
db.from_texts(['The drink was horrible'],embedding)
result = db.similarity_search(query = 'How was the drink', k = 2)
print(result[0].page_content)
print(result[1].page_content)
```


Any suggestions on how to reduce memory footprint and/or tensor-parallelism strategies?


## Errors

```bash
INFO:     127.0.0.1:44352 - "POST /embeddings HTTP/1.1" 200 OK
ERROR    2024-12-15 23:04:35,932 infinity_emb ERROR: CUDA   batch_handler.py:574
         out of memory. Tried to allocate 2.00 GiB. GPU 4                       
         has a total capacity of 39.38 GiB of which 813.38                      
         MiB is free. Including non-PyTorch memory, this                        
         process has 38.58 GiB memory in use. Of the                            
         allocated memory 34.07 GiB is allocated by                             
         PyTorch, and 4.00 GiB is reserved by PyTorch but                       
         unallocated. If reserved but unallocated memory is                     
         large try setting                                                      
         PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True                       
         to avoid fragmentation.  See documentation for                         
         Memory Management                                                      
         (https://pytorch.org/docs/stable/notes/cuda.html#e                     
         nvironment-variables)                                                  
         Traceback (most recent call last):                                     
           File                                                                 
         "/eagle/argonne_tpc/inference-gateway/infinityv0.0                     
         .71/lib/python3.11/site-packages/infinity_emb/infe                     
         rence/batch_handler.py", line 563, in _core_batch                      
             embed = self._model.encode_core(feat)                              
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                              
           File                                                                 
         "/eagle/argonne_tpc/inference-gateway/infinityv0.0                     
         .71/lib/python3.11/site-packages/infinity_emb/tran                     
         sformer/embedder/sentence_transformer.py", line                        
         120, in encode_core                                                    
             out: dict[str, "Tensor"] =                                         
         self.forward(features)                                                 
                                        ^^^^^^^^^^^^^^^^^^^                     
         ^^^                                                                    
           File                                                                 
         "/eagle/argonne_tpc/inference-gateway/infinityv0.0                     
         .71/lib/python3.11/site-packages/sentence_transfor                     
         mers/SentenceTransformer.py", line 690, in forward                     
             input = module(input, **module_kwargs)                             
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                             
           File                                                                 
         "/eagle/argonne_tpc/inference-gateway/infinityv0.0                     
         .71/lib/python3.11/site-packages/torch/nn/modules/                     
         module.py", line 1736, in _wrapped_call_impl                           
             return self._call_impl(*args, **kwargs)                            
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                            
           File                                                                 
         "/eagle/argonne_tpc/inference-gateway/infinityv0.0                     
         .71/lib/python3.11/site-packages/torch/nn/modules/                     
         module.py", line 1747, in _call_impl                                   
             return forward_call(*args, **kwargs)                               
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                               
           File                                                                 
         "/eagle/argonne_tpc/inference-gateway/infinityv0.0                     
         .71/lib/python3.11/site-packages/sentence_transfor                     
         mers/models/Transformer.py", line 393, in forward                      
             output_states =                                                    
         self.auto_model(**trans_features, **kwargs,                            
         return_dict=False)                                                     
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                     
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                       
           File                                                                 
         "/eagle/argonne_tpc/inference-gateway/infinityv0.0                     
         .71/lib/python3.11/site-packages/torch/nn/modules/                     
         module.py", line 1736, in _wrapped_call_impl                           
             return self._call_impl(*args, **kwargs)                            
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                            
           File                                                                 
         "/eagle/argonne_tpc/inference-gateway/infinityv0.0                     
         .71/lib/python3.11/site-packages/torch/nn/modules/                     
         module.py", line 1747, in _call_impl                                   
             return forward_call(*args, **kwargs)                               
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                               
           File                                                                 
         "/eagle/argonne_tpc/model_weights/modules/transfor                     
         mers_modules/nvidia/NV-Embed-v2/5130cf1daf847c1bac                     
         ee854a6ef1ca939e747fb2/modeling_nvembed.py", line                      
         406, in forward                                                        
             embeds = self.latent_attention_model(                              
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^                              
           File                                                                 
         "/eagle/argonne_tpc/inference-gateway/infinityv0.0                     
         .71/lib/python3.11/site-packages/torch/nn/modules/                     
         module.py", line 1736, in _wrapped_call_impl                           
             return self._call_impl(*args, **kwargs)                            
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                            
           File                                                                 
         "/eagle/argonne_tpc/inference-gateway/infinityv0.0                     
         .71/lib/python3.11/site-packages/torch/nn/modules/                     
         module.py", line 1747, in _call_impl                                   
             return forward_call(*args, **kwargs)                               
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                               
           File                                                                 
         "/eagle/argonne_tpc/model_weights/modules/transfor                     
         mers_modules/nvidia/NV-Embed-v2/5130cf1daf847c1bac                     
         ee854a6ef1ca939e747fb2/modeling_nvembed.py", line                      
         307, in forward                                                        
             hiddens = cross_attn(hiddens, context = x,                         
         mask = None) + hiddens                                                 
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                     
         ^^^^^^^^^                                                              
           File                                                                 
         "/eagle/argonne_tpc/inference-gateway/infinityv0.0                     
         .71/lib/python3.11/site-packages/torch/nn/modules/                     
         module.py", line 1736, in _wrapped_call_impl                           
             return self._call_impl(*args, **kwargs)                            
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                            
           File                                                                 
         "/eagle/argonne_tpc/inference-gateway/infinityv0.0                     
         .71/lib/python3.11/site-packages/torch/nn/modules/                     
         module.py", line 1747, in _call_impl                                   
             return forward_call(*args, **kwargs)                               
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                               
           File                                                                 
         "/eagle/argonne_tpc/model_weights/modules/transfor                     
         mers_modules/nvidia/NV-Embed-v2/5130cf1daf847c1bac                     
         ee854a6ef1ca939e747fb2/modeling_nvembed.py", line                      
         237, in forward                                                        
             return self.fn(x, **kwargs)                                        
                    ^^^^^^^^^^^^^^^^^^^^                                        
           File                                                                 
         "/eagle/argonne_tpc/inference-gateway/infinityv0.0                     
         .71/lib/python3.11/site-packages/torch/nn/modules/                     
         module.py", line 1736, in _wrapped_call_impl                           
             return self._call_impl(*args, **kwargs)                            
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                            
           File                                                                 
         "/eagle/argonne_tpc/inference-gateway/infinityv0.0                     
         .71/lib/python3.11/site-packages/torch/nn/modules/                     
         module.py", line 1747, in _call_impl                                   
             return forward_call(*args, **kwargs)                               
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                               
           File                                                                 
         "/eagle/argonne_tpc/model_weights/modules/transfor                     
         mers_modules/nvidia/NV-Embed-v2/5130cf1daf847c1bac                     
         ee854a6ef1ca939e747fb2/modeling_nvembed.py", line                      
         280, in forward                                                        
             out =                                                              
         torch.nn.functional.scaled_dot_product_attention(q                     
         , k, v)                                                                
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                     
         ^^^^^^^^^^^^^^^^^                                                      
         torch.OutOfMemoryError: CUDA out of memory. Tried                      
         to allocate 2.00 GiB. GPU 4 has a total capacity                       
         of 39.38 GiB of which 813.38 MiB is free.                              
         Including non-PyTorch memory, this process has                         
         38.58 GiB memory in use. Of the allocated memory                       
         34.07 GiB is allocated by PyTorch, and 4.00 GiB is                     
         reserved by PyTorch but unallocated. If reserved                       
         but unallocated memory is large try setting                            
         PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True                       
         to avoid fragmentation.  See documentation for                         
         Memory Management                                                      
         (https://pytorch.org/docs/stable/notes/cuda.html#e                     
         nvironment-variables)  
```

**Comment by michaelfeil** [comment]
nvidia/NV-Embed-v2 · Update configuration_nvembed.py (transformers + sentence-transformers) and infinity usagehuggingface.coMy PR was not merged. Here are some instructions.On Dec 15, 2024, at 21:36, Aditya Tanikanti ***@***.***> wrote:﻿
System Info
Infinity version: 0.0.71
***@***.*** ~]$ conda activate /eagle/argonne_tpc/inference-gateway/infinityv0.0.71
(2024-08-08//eagle/argonne_tpc/inference-gateway/infinityv0.0.71) ***@***.*** ~]$ infinity_emb v2 --help
INFO     2024-12-16 05:30:55,856 datasets INFO: PyTorch version 2.5.1 available.                                                                                                                          config.py:54

   OS version:     linux
   Model being used:  NV-Embed-V2                                                                                                                                                                                                                                                               
   Hardware: 8 NIVIDIA 40GB A100 GPUs

Is there tensor parallelism or some other way to mitigate memory issues when serving the model. We see it after a few requests in a tool calling example.
Information

 Docker + cli
 pip + cli
 pip + usage of Python interface

Tasks

 An officially supported CLI command
 My own modifications

Reproduction
Model serving.
infinity_emb v2 --host 127.0.0.1 --port 8000 --model-id nvidia/NV-Embed-v2 --device cuda --trust-remote-code 
Example call:
from openai import OpenAI
import base64
from langchain_chroma import Chroma
from authinfinityembeddings import AuthInfinityEmbeddings

# Load access token                                                                                                  
with open('access_token.txt', 'r') as file:
  access_token = file.read().strip()

url   = "https://data-portal-dev.cels.anl.gov/resource_server/sophia/infinity/v1"
model = "nvidia/NV-Embed-v2"


# Using Chroma to construct a vector database                                                                        

embedding = AuthInfinityEmbeddings(infinity_api_url = url,model = model, token = access_token)

db  = Chroma.from_texts(['The food was delicious and the waiter..','The cat was big'], embedding)
db.from_texts(['The drink was horrible'],embedding)
result = db.similarity_search(query = 'How was the drink', k = 2)
print(result[0].page_content)
print(result[1].page_content)

Any suggestions on how to reduce memory footprint and/or tensor-parallelism strategies?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by atanikan** [comment]
Hi @michaelfeil, Sorry I believe your reply is truncated and/or incomplete?

**Comment by taoari** [comment]
I encountered the same issue for `BAAI/bge-en-icl`. When I setup Infinity, it only used 30GB. When I ingest a collection of documents, it quickly grows to 46GB, and then get the OOM error.

**Comment by michaelfeil** [comment]
control `--batch-size 4` for activation memory. Its literally in the HuggingFace documentation

**Comment by michaelfeil** [comment]
https://huggingface.co/nvidia/NV-Embed-v2/discussions/30 TY

**Comment by michaelfeil** [comment]
@taoari https://huggingface.co/BAAI/bge-en-icl/discussions/9

**Comment by qdrddr** [comment]
Cannot run `BAAI/bge-en-icl` on my macOS 15
